---
vms:
  kiosk:
    count: 2
    role: kiosk
  gpfs:
    count: 1
    role: gpfs
    storageClassName: ibm-spectrum-scale-sample
    volumeMode: "Filesystem"
    urlSource: "docker://registry:5000/kubevirt/alpine-container-disk-demo:devel"